### ISSUE TITLE
您好，请问这个是装哪个系统？11还是10.15  我试了一下，安装完无限重启，是什么地方需要设置吗？？谢谢

### ISSUE THREAD

**Issue by xisohi** [huhugh221/Efi-Hackintosh-SVS1512X9E-B-VAIO#8]
您好，请问这个是装哪个系统？11还是10.15  我试了一下，安装完无限重启，是什么地方需要设置吗？？谢谢

**Comment by huhugh221** [comment]
No need to set it, get a full installer, not a recovery image
